#include "theme.h"

namespace aqua::ui::theme {

// Phase 1: built-in Montserrat as placeholder.
// Phase 4 will replace these accessors with Roboto Latin+Cyrillic faces
// generated by lv_font_conv (font_roboto_14/18/24/32).
const lv_font_t* font_small()   { return &lv_font_montserrat_14; }
const lv_font_t* font_body()    { return &lv_font_montserrat_18; }
const lv_font_t* font_heading() { return &lv_font_montserrat_18; }
const lv_font_t* font_large()   { return &lv_font_montserrat_18; }

}  // namespace aqua::ui::theme
